return {
PlaceObj('ModItemMissionSponsorPreset', {
	AdvancedStirlingGenerator = 1,
	Drone = 6,
	DroneHub = 1,
	Electronics = 10,
	ExplorerRover = 1,
	MachineParts = 15,
	MoistureVaporator = 1,
	OrbitalProbe = 4,
	Polymers = 15,
	RCRover = 1,
	RCTransport = 1,
	SortKey = 1001,
	banners_name = "IMM",
	cargo = 70000,
	comment = "National Mars Mission",
	default_logo = "IMM",
	difficulty = T(139794439334, --[[ModItemMissionSponsorPreset Default FF_NationalMarsMission difficulty]] "Very Easy"),
	display_name = T(204478408777, --[[ModItemMissionSponsorPreset Default FF_NationalMarsMission display_name]] "National Mars Mission"),
	effect = T(348697016896, --[[ModItemMissionSponsorPreset Default FF_NationalMarsMission effect]] "Research per Sol: 300\nRare Metals price: $<ExportPricePreciousMetals> M\n\n- <color em>Zeus Rocket</color> - increased rocket payload (<cargo> kg)\n- <color em>Advanced Stirling Generator</color> - generates power and can protect from Cold Waves\n- Colonists never get Earthsick\n- Food supply from Passenger Rockets increased (x10)\n- Rockets synthesize Fuel\n- Start with a Self-Sufficient Dome prefab"),
	flavor = T(954750318108, --[[ModItemMissionSponsorPreset Default FF_NationalMarsMission flavor]] "Recommended for first-time players"),
	funding = 6000,
	goal_1_param_1 = "30",
	goal_4_param_1 = "3000",
	goal_5_param_1 = "10",
	goal_image_1 = "UI/Messages/Goals/mission_goal_09.tga",
	goal_image_2 = "UI/Messages/Goals/mission_goal_06.tga",
	goal_image_3 = "UI/Messages/Goals/mission_goal_05.tga",
	goal_image_4 = "UI/Messages/Goals/mission_goal_08.tga",
	goal_image_5 = "UI/Messages/Goals/mission_goal_10.tga",
	goal_pin_image_1 = "UI/Icons/Buildings/dome.tga",
	goal_pin_image_2 = "UI/Icons/Buildings/supply_pod.tga",
	goal_pin_image_3 = "UI/Icons/Colonists/Femaleengineer.tga",
	goal_pin_image_4 = "UI/Icons/Colonists/Femalescientist.tga",
	goal_pin_image_5 = "UI/Icons/Buildings/mega_dome.tga",
	group = "Default",
	id = "FF_NationalMarsMission",
	initial_applicants = 200,
	initial_rockets = 1,
	initial_techs_unlocked = 1,
	lock_name1 = "AdvancedStirlingGenerator",
	lock_value1 = "unlocked",
	name = "FF_NationalMarsMission",
	pod_class = "SupplyPod",
	research_points = 300,
	reward_effect_1 = PlaceObj('RewardPrefab', {
		'Amount', 1,
		'Prefab', "DomeBasic",
	}),
	reward_effect_2 = PlaceObj('RewardSupplyPods', {
		'Amount', 5,
	}),
	reward_effect_3 = PlaceObj('RewardApplicants', {
		'Amount', 30,
		'Specialization', "engineer",
	}),
	reward_effect_4 = PlaceObj('RewardApplicants', {
		'Amount', 30,
		'Specialization', "scientist",
	}),
	reward_effect_5 = PlaceObj('RewardPrefab', {
		'Amount', 1,
		'Prefab', "DomeMega",
	}),
	rocket_class = "ZeusRocket",
	sponsor_goal_1 = "Colonists",
	sponsor_goal_2 = "ChildBorn",
	sponsor_goal_3 = "OneOfEachFactory",
	sponsor_goal_4 = "GenerateDailyRP",
	sponsor_goal_5 = "MartianbornEducate",
	sponsor_nation_name1 = "American",
	sponsor_nation_name2 = "German",
	sponsor_nation_name3 = "Russian",
	sponsor_nation_name4 = "Chinese",
	sponsor_nation_name5 = "Indian",
	sponsor_nation_name6 = "Bulgarian",
	sponsor_nation_name7 = "Swedish",
	sponsor_nation_name8 = "French",
	sponsor_nation_percent1 = 20,
	sponsor_nation_percent2 = 5,
	sponsor_nation_percent3 = 5,
	sponsor_nation_percent4 = 20,
	sponsor_nation_percent5 = 20,
	sponsor_nation_percent6 = 5,
	sponsor_nation_percent7 = 5,
	sponsor_nation_percent8 = 5,
	PlaceObj('Effect_ModifyLabel', {
		Amount = 9000,
		Label = "Consts",
		Prop = "FoodPerRocketPassenger",
	}),
	PlaceObj('Effect_GrantPrefab', {
		Prefab = "SelfSufficientDome",
	}),
}),
}
